# Generated by Django 5.1.2 on 2024-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisesession",
            name="sets",
            field=models.IntegerField(default=1),
        ),
    ]
