# Generated by Django 5.1.2 on 2024-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_exercisesession_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciselog",
            name="exercise_session",
            field=models.ForeignKey(
                default=30,
                on_delete=django.db.models.deletion.CASCADE,
                to="workout.exercisesession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="repeat_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="exercisesession",
            name="workout_session",
            field=models.ForeignKey(
                default=30,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_sessions",
                to="workout.workoutsession",
            ),
        ),
    ]
