# Generated by Django 5.1.2 on 2024-10-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0003_exerciselog_exercise_session_workout_repeat_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisesession",
            name="workout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_sessions",
                to="workout.workoutsession",
            ),
        ),
    ]
